[tools]
pre-commit = "4.3.0"
python = "3.12.11"

[tasks.dev]
description = "setup development environment"
run = """
npm run compile
"""

[tasks.optimize]
description = "build optimized bundle"
run = """
npm run package
"""

[tasks.package]
description = "create vsix file"
args = ["version"]
depends = ["dev"]
run = """
vsce package --out tombo-${version}.vsix
"""

[tasks.publish]
description = "uploads to marketplace"
args = ["version"]
run = """
vsce publish ${version}
"""
